using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WorkForce1API.Utils
{
    public class clsConstants
    {

        public static string Token = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjdFRjg0OERDRDA3Njc5ODVCMDlCNTZCNkIxMEU0NDJBQkMyREE3NEEiLCJ4NXQiOiJmdmhJM05CMmVZV3dtMWEyc1E1RUtyd3RwMG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJUQU1TIiwiaXNzIjoiaHR0cHM6Ly9xYS13b3JrZm9yY2VvbmUuc2VkZ3dpY2suY29tIiwiZXhwIjoxNzA4Mzg1MDAzLCJpYXQiOjE3MDgzODQ0MDMsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJTQ01TTkFcXFN1bWFuYS5SeWFsaSIsIldGMS5DbGluaWNhbEludGVyYWN0aW9ucy5SZWFkIjoiMjI4NSIsIldGMS5DbGluaWNhbEludGVyYWN0aW9ucy5Xcml0ZSI6IjIyODUiLCJXRjEuV29ya2xvYWRRdWV1ZS5SZWFkIjoiMjI4NSIsIldGMS5UYXNrTWFuYWdlbWVudC5SZWFkIjoiMjI4NSIsIldGMS5UYXNrTWFuYWdlbWVudC5DbGluaWNhbC5SZWFkIjoiMjI4NSIsIldGMS5UYXNrTWFuYWdlbWVudC5Xcml0ZSI6IjIyODUiLCJXRjEuVXNlci5SZWFkIjoiUUFUZXN0MDEiLCJXRjEuVXNlci5Xcml0ZSI6IlFBVGVzdDAxIiwiV0YxLkF0dHJpYnV0ZXMuTWFuYWdlbWVudExldmVsIjoyLCJXRjEuQXR0cmlidXRlcy5KdXJpc1VzZXJuYW1lIjoiUUFUZXN0MDEiLCJXRjEuQXR0cmlidXRlcy5HaXZlbk5hbWUiOiIrUUFUZXN0MDEiLCJXRjEuQXR0cmlidXRlcy5GYW1pbHlOYW1lIjoiK1FBVGVzdDAxIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTExMjc5NDgyOTgtMTMyNDEwNjYzNS0zMTE1NzY2NDctNjg2MzMwIiwibmJmIjoxNzA4Mzg0NDA0fQ.lgeSKt5ZyVmVpBpD5MLFnH__4BCXMkQ_PHQHvhxGhnNF-ZgUSv_h0-jnIdyjw4O0xjSbypyhiFu67Ymb_S0TL8RPLupA7o15xqCr2oczNFHOG8F4LSbidP2yc3NnzrwCa8zGhhyx4sWrX8LImiO6nFgB0HkUYIiLvIdjXeKBLaUvGuyc6JePOfAdUvUb-0yU4tQ6Z1GLXZlma33u0ZBSlE0QEFhiLsU5EGTkeZE430qXCJLLJ9g3tf9dUsAdSqCx_nnMwtRjLDW8TWC6oAcf-C4G79_yl0fa1ZWti8kEMCMLrO_23Il3hJO6hovJ50ZH5VHqzcG9CGbF56kcXDU6zw";
        public static string BaseURL = "https://tams-testworkforceone.sedgwickcms.com/tams.api/api/WorkforceOne/";
        public static string JsonPath = @"C:\AutomationProjects\Data\JsonFiles\";
    }
}
